name             'cookbook_analogj_test'
license          'MIT'
description      'Installs/Configures cookbook_analogj_test'
long_description 'Installs/Configures cookbook_analogj_test'
version          '0.1.17'
maintainer       'Test User'
maintainer_email 'test@test.com'
issues_url        'http://www.example.com'
source_url        'http://www.example.com'
