name             'test_cookbook'
maintainer       'Copyright 2014, Adobe Systems Incorporated'
maintainer_email 'serenity@adobe.com'
license          'All rights reserved'
description      'Installs/Configures test_cookbook'
long_description 'Installs/Configures test_cookbook'
version          '0.1.2'
